name: agro_farm
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

  get: ^3.24.0
  google_fonts: ^0.3.5
  url_launcher: ^5.7.10
  intl: ^0.16.1

  cached_network_image: ^2.5.0
  font_awesome_flutter: ^8.11.0

  fluttertoast: ^7.1.6

  #Firebase dependencies
  firebase_auth: ^0.20.0+1
  firebase_core: ^0.7.0
  cloud_firestore: ^0.16.0

  tflite: ^1.1.1

  pretty_qr_code: ^1.0.1

  qr_flutter: ^3.2.0

  flutter_search_bar: ^2.1.0

  sqflite: ^1.3.2+3

  tezster_dart: ^2.0.0

  ml_algo: ^15.6.3
  ml_dataframe: ^0.4.0
  ml_preprocessing: ^5.2.2

  qr_code_scanner: ^0.3.5


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - images/clouds.jpg
   - images/bg.jpg
   - images/fields.jpg
   - images/bajra.jpg
   - images/barley.jpg
   - images/chilli.jpg
   - images/gram.jpg
   - images/jowar.jpg
   - images/maize.jpg
   - images/moong.jpg
   - images/mustard.jpg
   - images/off season vegetables.jpg
   - images/oilseeds.jpeg
   - images/pulses.jpg
   - images/ragi.jpg
   - images/redgram.jpg
   - images/tur.jpg
   - images/urad.jpg
   - images/wheat.jpg
   - images/farmer.jpg
   - images/back.jpg
   - images/crop.png
   - images/cropsback.jpg
   - images/rapeseed.jpg
   - images/seedicon.jpg
   - images/fertilizericon.png
   - images/rice.jpg
   - images/tea.jpg
   - images/millet.jpg
   - images/lentil.jpg
   - images/jute.jpg
   - images/coffee.jpg
   - images/groundnut.jpg
   - images/peas.jpg
   - images/rubber.jpg
   - images/sugarcane.jpg
   - images/tobacco.jpg
   - images/kidneybeans.jpg
   - images/mothbeans.jpg
   - images/coconut.jpg
   - images/blackgram.jpeg
   - images/adzukibeans.jpg
   - images/pigeonpeas.png
   - images/chickpea.jpg
   - images/apple.jpg
   - images/mango.jpg
   - images/muskmelon.jpeg
   - images/orange.jpg
   - images/papaya.jpg
   - images/pomegranate.jpg
   - images/watermelon.jpg
   - images/grape.jpg
   - images/jute.jpg
   - images/seedicon.png
   - images/kidneybeans.jpg
   - images/organicliquid.jpg
   - images/bonemeal.jpg
   - images/compost.jpg
   - images/manure.jpg
   - images/rockphosphate.png
   - images/cottonseed.jpg
   - images/alfalfa.png
   - images/bloodmeal.jpg
   - images/feathermeal.jpg
   - images/liquidkelp.jpg

   - images/farmcure.png

   
   





  #   - images/a_dot_ham.jpeg

   - assets/crop_detection.tflite
   - assets/labels.txt
   - assets/crop_prediction_dataset.csv

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
